### ISSUE TITLE
twui fails to start with error 'raw.map is not a function'

### ISSUE THREAD

**Issue by bjornreppen** [rampantmonkey/twui#59]
~/src/twui   master  bin/twui 
running at localhost:2718...
taskwarrior exited with status: 0
TypeError: raw.map is not a function
    at /home/b/src/twui/lib/task_fetcher.js:38:18
    at exports.when (/home/b/src/twui/node_modules/promised-io/promise.js:370:29)
    at toTasks (/home/b/src/twui/lib/task_fetcher.js:34:3)
    at next (/home/b/src/twui/node_modules/promised-io/promise.js:584:17)
    at notify (/home/b/src/twui/node_modules/promised-io/promise.js:201:22)
    at notifyAll (/home/b/src/twui/node_modules/promised-io/promise.js:180:5)
    at Promise.Deferred.resolve.callback.emitSuccess (/home/b/src/twui/node_modules/promised-io/promise.js:223:3)
    at Socket.<anonymous> (/home/b/src/twui/lib/task_fetcher.js:20:14)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)

**Comment by charrismatic** [comment]
`raw.map is not a function`
I checked the value that was being passed in here, and it was a string type instead of an array.  JSON.parse() returned the correct object
